// Code generated by protoc-gen-go.
// source: QJournalProtocol.proto
// DO NOT EDIT!

/*
Package hadoop_hdfs_qjournal is a generated protocol buffer package.

It is generated from these files:
	QJournalProtocol.proto

It has these top-level messages:
	JournalIdProto
	RequestInfoProto
	SegmentStateProto
	PersistedRecoveryPaxosData
	JournalRequestProto
	JournalResponseProto
	HeartbeatRequestProto
	HeartbeatResponseProto
	StartLogSegmentRequestProto
	StartLogSegmentResponseProto
	FinalizeLogSegmentRequestProto
	FinalizeLogSegmentResponseProto
	PurgeLogsRequestProto
	PurgeLogsResponseProto
	IsFormattedRequestProto
	IsFormattedResponseProto
	DiscardSegmentsRequestProto
	DiscardSegmentsResponseProto
	GetJournalCTimeRequestProto
	GetJournalCTimeResponseProto
	DoPreUpgradeRequestProto
	DoPreUpgradeResponseProto
	DoUpgradeRequestProto
	DoUpgradeResponseProto
	DoFinalizeRequestProto
	DoFinalizeResponseProto
	CanRollBackRequestProto
	CanRollBackResponseProto
	DoRollbackRequestProto
	DoRollbackResponseProto
	GetJournalStateRequestProto
	GetJournalStateResponseProto
	FormatRequestProto
	FormatResponseProto
	NewEpochRequestProto
	NewEpochResponseProto
	GetEditLogManifestRequestProto
	GetEditLogManifestResponseProto
	PrepareRecoveryRequestProto
	PrepareRecoveryResponseProto
	AcceptRecoveryRequestProto
	AcceptRecoveryResponseProto
*/
package hadoop_hdfs_qjournal

import proto "code.google.com/p/goprotobuf/proto"
import math "math"
import hadoop_hdfs "github.com/hortonworks/gohadoop/hdfs"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type JournalIdProto struct {
	Identifier       *string `protobuf:"bytes,1,req,name=identifier" json:"identifier,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *JournalIdProto) Reset()         { *m = JournalIdProto{} }
func (m *JournalIdProto) String() string { return proto.CompactTextString(m) }
func (*JournalIdProto) ProtoMessage()    {}

func (m *JournalIdProto) GetIdentifier() string {
	if m != nil && m.Identifier != nil {
		return *m.Identifier
	}
	return ""
}

type RequestInfoProto struct {
	JournalId       *JournalIdProto `protobuf:"bytes,1,req,name=journalId" json:"journalId,omitempty"`
	Epoch           *uint64         `protobuf:"varint,2,req,name=epoch" json:"epoch,omitempty"`
	IpcSerialNumber *uint64         `protobuf:"varint,3,req,name=ipcSerialNumber" json:"ipcSerialNumber,omitempty"`
	// Whenever a writer makes a request, it informs
	// the node of the latest committed txid. This may
	// be higher than the transaction data included in the
	// request itself, eg in the case that the node has
	// fallen behind.
	CommittedTxId    *uint64 `protobuf:"varint,4,opt,name=committedTxId" json:"committedTxId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RequestInfoProto) Reset()         { *m = RequestInfoProto{} }
func (m *RequestInfoProto) String() string { return proto.CompactTextString(m) }
func (*RequestInfoProto) ProtoMessage()    {}

func (m *RequestInfoProto) GetJournalId() *JournalIdProto {
	if m != nil {
		return m.JournalId
	}
	return nil
}

func (m *RequestInfoProto) GetEpoch() uint64 {
	if m != nil && m.Epoch != nil {
		return *m.Epoch
	}
	return 0
}

func (m *RequestInfoProto) GetIpcSerialNumber() uint64 {
	if m != nil && m.IpcSerialNumber != nil {
		return *m.IpcSerialNumber
	}
	return 0
}

func (m *RequestInfoProto) GetCommittedTxId() uint64 {
	if m != nil && m.CommittedTxId != nil {
		return *m.CommittedTxId
	}
	return 0
}

type SegmentStateProto struct {
	StartTxId        *uint64 `protobuf:"varint,1,req,name=startTxId" json:"startTxId,omitempty"`
	EndTxId          *uint64 `protobuf:"varint,2,req,name=endTxId" json:"endTxId,omitempty"`
	IsInProgress     *bool   `protobuf:"varint,3,req,name=isInProgress" json:"isInProgress,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SegmentStateProto) Reset()         { *m = SegmentStateProto{} }
func (m *SegmentStateProto) String() string { return proto.CompactTextString(m) }
func (*SegmentStateProto) ProtoMessage()    {}

func (m *SegmentStateProto) GetStartTxId() uint64 {
	if m != nil && m.StartTxId != nil {
		return *m.StartTxId
	}
	return 0
}

func (m *SegmentStateProto) GetEndTxId() uint64 {
	if m != nil && m.EndTxId != nil {
		return *m.EndTxId
	}
	return 0
}

func (m *SegmentStateProto) GetIsInProgress() bool {
	if m != nil && m.IsInProgress != nil {
		return *m.IsInProgress
	}
	return false
}

// *
// The storage format used on local disk for previously
// accepted decisions.
type PersistedRecoveryPaxosData struct {
	SegmentState     *SegmentStateProto `protobuf:"bytes,1,req,name=segmentState" json:"segmentState,omitempty"`
	AcceptedInEpoch  *uint64            `protobuf:"varint,2,req,name=acceptedInEpoch" json:"acceptedInEpoch,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *PersistedRecoveryPaxosData) Reset()         { *m = PersistedRecoveryPaxosData{} }
func (m *PersistedRecoveryPaxosData) String() string { return proto.CompactTextString(m) }
func (*PersistedRecoveryPaxosData) ProtoMessage()    {}

func (m *PersistedRecoveryPaxosData) GetSegmentState() *SegmentStateProto {
	if m != nil {
		return m.SegmentState
	}
	return nil
}

func (m *PersistedRecoveryPaxosData) GetAcceptedInEpoch() uint64 {
	if m != nil && m.AcceptedInEpoch != nil {
		return *m.AcceptedInEpoch
	}
	return 0
}

type JournalRequestProto struct {
	ReqInfo          *RequestInfoProto `protobuf:"bytes,1,req,name=reqInfo" json:"reqInfo,omitempty"`
	FirstTxnId       *uint64           `protobuf:"varint,2,req,name=firstTxnId" json:"firstTxnId,omitempty"`
	NumTxns          *uint32           `protobuf:"varint,3,req,name=numTxns" json:"numTxns,omitempty"`
	Records          []byte            `protobuf:"bytes,4,req,name=records" json:"records,omitempty"`
	SegmentTxnId     *uint64           `protobuf:"varint,5,req,name=segmentTxnId" json:"segmentTxnId,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *JournalRequestProto) Reset()         { *m = JournalRequestProto{} }
func (m *JournalRequestProto) String() string { return proto.CompactTextString(m) }
func (*JournalRequestProto) ProtoMessage()    {}

func (m *JournalRequestProto) GetReqInfo() *RequestInfoProto {
	if m != nil {
		return m.ReqInfo
	}
	return nil
}

func (m *JournalRequestProto) GetFirstTxnId() uint64 {
	if m != nil && m.FirstTxnId != nil {
		return *m.FirstTxnId
	}
	return 0
}

func (m *JournalRequestProto) GetNumTxns() uint32 {
	if m != nil && m.NumTxns != nil {
		return *m.NumTxns
	}
	return 0
}

func (m *JournalRequestProto) GetRecords() []byte {
	if m != nil {
		return m.Records
	}
	return nil
}

func (m *JournalRequestProto) GetSegmentTxnId() uint64 {
	if m != nil && m.SegmentTxnId != nil {
		return *m.SegmentTxnId
	}
	return 0
}

type JournalResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *JournalResponseProto) Reset()         { *m = JournalResponseProto{} }
func (m *JournalResponseProto) String() string { return proto.CompactTextString(m) }
func (*JournalResponseProto) ProtoMessage()    {}

type HeartbeatRequestProto struct {
	ReqInfo          *RequestInfoProto `protobuf:"bytes,1,req,name=reqInfo" json:"reqInfo,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *HeartbeatRequestProto) Reset()         { *m = HeartbeatRequestProto{} }
func (m *HeartbeatRequestProto) String() string { return proto.CompactTextString(m) }
func (*HeartbeatRequestProto) ProtoMessage()    {}

func (m *HeartbeatRequestProto) GetReqInfo() *RequestInfoProto {
	if m != nil {
		return m.ReqInfo
	}
	return nil
}

type HeartbeatResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *HeartbeatResponseProto) Reset()         { *m = HeartbeatResponseProto{} }
func (m *HeartbeatResponseProto) String() string { return proto.CompactTextString(m) }
func (*HeartbeatResponseProto) ProtoMessage()    {}

// *
// startLogSegment()
type StartLogSegmentRequestProto struct {
	ReqInfo          *RequestInfoProto `protobuf:"bytes,1,req,name=reqInfo" json:"reqInfo,omitempty"`
	Txid             *uint64           `protobuf:"varint,2,req,name=txid" json:"txid,omitempty"`
	LayoutVersion    *int32            `protobuf:"zigzag32,3,opt,name=layoutVersion" json:"layoutVersion,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *StartLogSegmentRequestProto) Reset()         { *m = StartLogSegmentRequestProto{} }
func (m *StartLogSegmentRequestProto) String() string { return proto.CompactTextString(m) }
func (*StartLogSegmentRequestProto) ProtoMessage()    {}

func (m *StartLogSegmentRequestProto) GetReqInfo() *RequestInfoProto {
	if m != nil {
		return m.ReqInfo
	}
	return nil
}

func (m *StartLogSegmentRequestProto) GetTxid() uint64 {
	if m != nil && m.Txid != nil {
		return *m.Txid
	}
	return 0
}

func (m *StartLogSegmentRequestProto) GetLayoutVersion() int32 {
	if m != nil && m.LayoutVersion != nil {
		return *m.LayoutVersion
	}
	return 0
}

type StartLogSegmentResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *StartLogSegmentResponseProto) Reset()         { *m = StartLogSegmentResponseProto{} }
func (m *StartLogSegmentResponseProto) String() string { return proto.CompactTextString(m) }
func (*StartLogSegmentResponseProto) ProtoMessage()    {}

// *
// finalizeLogSegment()
type FinalizeLogSegmentRequestProto struct {
	ReqInfo          *RequestInfoProto `protobuf:"bytes,1,req,name=reqInfo" json:"reqInfo,omitempty"`
	StartTxId        *uint64           `protobuf:"varint,2,req,name=startTxId" json:"startTxId,omitempty"`
	EndTxId          *uint64           `protobuf:"varint,3,req,name=endTxId" json:"endTxId,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *FinalizeLogSegmentRequestProto) Reset()         { *m = FinalizeLogSegmentRequestProto{} }
func (m *FinalizeLogSegmentRequestProto) String() string { return proto.CompactTextString(m) }
func (*FinalizeLogSegmentRequestProto) ProtoMessage()    {}

func (m *FinalizeLogSegmentRequestProto) GetReqInfo() *RequestInfoProto {
	if m != nil {
		return m.ReqInfo
	}
	return nil
}

func (m *FinalizeLogSegmentRequestProto) GetStartTxId() uint64 {
	if m != nil && m.StartTxId != nil {
		return *m.StartTxId
	}
	return 0
}

func (m *FinalizeLogSegmentRequestProto) GetEndTxId() uint64 {
	if m != nil && m.EndTxId != nil {
		return *m.EndTxId
	}
	return 0
}

type FinalizeLogSegmentResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *FinalizeLogSegmentResponseProto) Reset()         { *m = FinalizeLogSegmentResponseProto{} }
func (m *FinalizeLogSegmentResponseProto) String() string { return proto.CompactTextString(m) }
func (*FinalizeLogSegmentResponseProto) ProtoMessage()    {}

// *
// purgeLogs()
type PurgeLogsRequestProto struct {
	ReqInfo          *RequestInfoProto `protobuf:"bytes,1,req,name=reqInfo" json:"reqInfo,omitempty"`
	MinTxIdToKeep    *uint64           `protobuf:"varint,2,req,name=minTxIdToKeep" json:"minTxIdToKeep,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *PurgeLogsRequestProto) Reset()         { *m = PurgeLogsRequestProto{} }
func (m *PurgeLogsRequestProto) String() string { return proto.CompactTextString(m) }
func (*PurgeLogsRequestProto) ProtoMessage()    {}

func (m *PurgeLogsRequestProto) GetReqInfo() *RequestInfoProto {
	if m != nil {
		return m.ReqInfo
	}
	return nil
}

func (m *PurgeLogsRequestProto) GetMinTxIdToKeep() uint64 {
	if m != nil && m.MinTxIdToKeep != nil {
		return *m.MinTxIdToKeep
	}
	return 0
}

type PurgeLogsResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *PurgeLogsResponseProto) Reset()         { *m = PurgeLogsResponseProto{} }
func (m *PurgeLogsResponseProto) String() string { return proto.CompactTextString(m) }
func (*PurgeLogsResponseProto) ProtoMessage()    {}

// *
// isFormatted()
type IsFormattedRequestProto struct {
	Jid              *JournalIdProto `protobuf:"bytes,1,req,name=jid" json:"jid,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *IsFormattedRequestProto) Reset()         { *m = IsFormattedRequestProto{} }
func (m *IsFormattedRequestProto) String() string { return proto.CompactTextString(m) }
func (*IsFormattedRequestProto) ProtoMessage()    {}

func (m *IsFormattedRequestProto) GetJid() *JournalIdProto {
	if m != nil {
		return m.Jid
	}
	return nil
}

type IsFormattedResponseProto struct {
	IsFormatted      *bool  `protobuf:"varint,1,req,name=isFormatted" json:"isFormatted,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *IsFormattedResponseProto) Reset()         { *m = IsFormattedResponseProto{} }
func (m *IsFormattedResponseProto) String() string { return proto.CompactTextString(m) }
func (*IsFormattedResponseProto) ProtoMessage()    {}

func (m *IsFormattedResponseProto) GetIsFormatted() bool {
	if m != nil && m.IsFormatted != nil {
		return *m.IsFormatted
	}
	return false
}

// *
// discardSegments()
type DiscardSegmentsRequestProto struct {
	Jid              *JournalIdProto `protobuf:"bytes,1,req,name=jid" json:"jid,omitempty"`
	StartTxId        *uint64         `protobuf:"varint,2,req,name=startTxId" json:"startTxId,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *DiscardSegmentsRequestProto) Reset()         { *m = DiscardSegmentsRequestProto{} }
func (m *DiscardSegmentsRequestProto) String() string { return proto.CompactTextString(m) }
func (*DiscardSegmentsRequestProto) ProtoMessage()    {}

func (m *DiscardSegmentsRequestProto) GetJid() *JournalIdProto {
	if m != nil {
		return m.Jid
	}
	return nil
}

func (m *DiscardSegmentsRequestProto) GetStartTxId() uint64 {
	if m != nil && m.StartTxId != nil {
		return *m.StartTxId
	}
	return 0
}

type DiscardSegmentsResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *DiscardSegmentsResponseProto) Reset()         { *m = DiscardSegmentsResponseProto{} }
func (m *DiscardSegmentsResponseProto) String() string { return proto.CompactTextString(m) }
func (*DiscardSegmentsResponseProto) ProtoMessage()    {}

// *
// getJournalCTime()
type GetJournalCTimeRequestProto struct {
	Jid              *JournalIdProto `protobuf:"bytes,1,req,name=jid" json:"jid,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *GetJournalCTimeRequestProto) Reset()         { *m = GetJournalCTimeRequestProto{} }
func (m *GetJournalCTimeRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetJournalCTimeRequestProto) ProtoMessage()    {}

func (m *GetJournalCTimeRequestProto) GetJid() *JournalIdProto {
	if m != nil {
		return m.Jid
	}
	return nil
}

type GetJournalCTimeResponseProto struct {
	ResultCTime      *int64 `protobuf:"varint,1,req,name=resultCTime" json:"resultCTime,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetJournalCTimeResponseProto) Reset()         { *m = GetJournalCTimeResponseProto{} }
func (m *GetJournalCTimeResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetJournalCTimeResponseProto) ProtoMessage()    {}

func (m *GetJournalCTimeResponseProto) GetResultCTime() int64 {
	if m != nil && m.ResultCTime != nil {
		return *m.ResultCTime
	}
	return 0
}

// *
// doPreUpgrade()
type DoPreUpgradeRequestProto struct {
	Jid              *JournalIdProto `protobuf:"bytes,1,req,name=jid" json:"jid,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *DoPreUpgradeRequestProto) Reset()         { *m = DoPreUpgradeRequestProto{} }
func (m *DoPreUpgradeRequestProto) String() string { return proto.CompactTextString(m) }
func (*DoPreUpgradeRequestProto) ProtoMessage()    {}

func (m *DoPreUpgradeRequestProto) GetJid() *JournalIdProto {
	if m != nil {
		return m.Jid
	}
	return nil
}

type DoPreUpgradeResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *DoPreUpgradeResponseProto) Reset()         { *m = DoPreUpgradeResponseProto{} }
func (m *DoPreUpgradeResponseProto) String() string { return proto.CompactTextString(m) }
func (*DoPreUpgradeResponseProto) ProtoMessage()    {}

// *
// doUpgrade()
type DoUpgradeRequestProto struct {
	Jid              *JournalIdProto               `protobuf:"bytes,1,req,name=jid" json:"jid,omitempty"`
	SInfo            *hadoop_hdfs.StorageInfoProto `protobuf:"bytes,2,req,name=sInfo" json:"sInfo,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *DoUpgradeRequestProto) Reset()         { *m = DoUpgradeRequestProto{} }
func (m *DoUpgradeRequestProto) String() string { return proto.CompactTextString(m) }
func (*DoUpgradeRequestProto) ProtoMessage()    {}

func (m *DoUpgradeRequestProto) GetJid() *JournalIdProto {
	if m != nil {
		return m.Jid
	}
	return nil
}

func (m *DoUpgradeRequestProto) GetSInfo() *hadoop_hdfs.StorageInfoProto {
	if m != nil {
		return m.SInfo
	}
	return nil
}

type DoUpgradeResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *DoUpgradeResponseProto) Reset()         { *m = DoUpgradeResponseProto{} }
func (m *DoUpgradeResponseProto) String() string { return proto.CompactTextString(m) }
func (*DoUpgradeResponseProto) ProtoMessage()    {}

// *
// doFinalize()
type DoFinalizeRequestProto struct {
	Jid              *JournalIdProto `protobuf:"bytes,1,req,name=jid" json:"jid,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *DoFinalizeRequestProto) Reset()         { *m = DoFinalizeRequestProto{} }
func (m *DoFinalizeRequestProto) String() string { return proto.CompactTextString(m) }
func (*DoFinalizeRequestProto) ProtoMessage()    {}

func (m *DoFinalizeRequestProto) GetJid() *JournalIdProto {
	if m != nil {
		return m.Jid
	}
	return nil
}

type DoFinalizeResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *DoFinalizeResponseProto) Reset()         { *m = DoFinalizeResponseProto{} }
func (m *DoFinalizeResponseProto) String() string { return proto.CompactTextString(m) }
func (*DoFinalizeResponseProto) ProtoMessage()    {}

// *
// canRollBack()
type CanRollBackRequestProto struct {
	Jid                 *JournalIdProto               `protobuf:"bytes,1,req,name=jid" json:"jid,omitempty"`
	Storage             *hadoop_hdfs.StorageInfoProto `protobuf:"bytes,2,req,name=storage" json:"storage,omitempty"`
	PrevStorage         *hadoop_hdfs.StorageInfoProto `protobuf:"bytes,3,req,name=prevStorage" json:"prevStorage,omitempty"`
	TargetLayoutVersion *int32                        `protobuf:"varint,4,req,name=targetLayoutVersion" json:"targetLayoutVersion,omitempty"`
	XXX_unrecognized    []byte                        `json:"-"`
}

func (m *CanRollBackRequestProto) Reset()         { *m = CanRollBackRequestProto{} }
func (m *CanRollBackRequestProto) String() string { return proto.CompactTextString(m) }
func (*CanRollBackRequestProto) ProtoMessage()    {}

func (m *CanRollBackRequestProto) GetJid() *JournalIdProto {
	if m != nil {
		return m.Jid
	}
	return nil
}

func (m *CanRollBackRequestProto) GetStorage() *hadoop_hdfs.StorageInfoProto {
	if m != nil {
		return m.Storage
	}
	return nil
}

func (m *CanRollBackRequestProto) GetPrevStorage() *hadoop_hdfs.StorageInfoProto {
	if m != nil {
		return m.PrevStorage
	}
	return nil
}

func (m *CanRollBackRequestProto) GetTargetLayoutVersion() int32 {
	if m != nil && m.TargetLayoutVersion != nil {
		return *m.TargetLayoutVersion
	}
	return 0
}

type CanRollBackResponseProto struct {
	CanRollBack      *bool  `protobuf:"varint,1,req,name=canRollBack" json:"canRollBack,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CanRollBackResponseProto) Reset()         { *m = CanRollBackResponseProto{} }
func (m *CanRollBackResponseProto) String() string { return proto.CompactTextString(m) }
func (*CanRollBackResponseProto) ProtoMessage()    {}

func (m *CanRollBackResponseProto) GetCanRollBack() bool {
	if m != nil && m.CanRollBack != nil {
		return *m.CanRollBack
	}
	return false
}

// *
// doRollback()
type DoRollbackRequestProto struct {
	Jid              *JournalIdProto `protobuf:"bytes,1,req,name=jid" json:"jid,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *DoRollbackRequestProto) Reset()         { *m = DoRollbackRequestProto{} }
func (m *DoRollbackRequestProto) String() string { return proto.CompactTextString(m) }
func (*DoRollbackRequestProto) ProtoMessage()    {}

func (m *DoRollbackRequestProto) GetJid() *JournalIdProto {
	if m != nil {
		return m.Jid
	}
	return nil
}

type DoRollbackResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *DoRollbackResponseProto) Reset()         { *m = DoRollbackResponseProto{} }
func (m *DoRollbackResponseProto) String() string { return proto.CompactTextString(m) }
func (*DoRollbackResponseProto) ProtoMessage()    {}

// *
// getJournalState()
type GetJournalStateRequestProto struct {
	Jid              *JournalIdProto `protobuf:"bytes,1,req,name=jid" json:"jid,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *GetJournalStateRequestProto) Reset()         { *m = GetJournalStateRequestProto{} }
func (m *GetJournalStateRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetJournalStateRequestProto) ProtoMessage()    {}

func (m *GetJournalStateRequestProto) GetJid() *JournalIdProto {
	if m != nil {
		return m.Jid
	}
	return nil
}

type GetJournalStateResponseProto struct {
	LastPromisedEpoch *uint64 `protobuf:"varint,1,req,name=lastPromisedEpoch" json:"lastPromisedEpoch,omitempty"`
	// Deprecated by fromURL
	HttpPort         *uint32 `protobuf:"varint,2,req,name=httpPort" json:"httpPort,omitempty"`
	FromURL          *string `protobuf:"bytes,3,opt,name=fromURL" json:"fromURL,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetJournalStateResponseProto) Reset()         { *m = GetJournalStateResponseProto{} }
func (m *GetJournalStateResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetJournalStateResponseProto) ProtoMessage()    {}

func (m *GetJournalStateResponseProto) GetLastPromisedEpoch() uint64 {
	if m != nil && m.LastPromisedEpoch != nil {
		return *m.LastPromisedEpoch
	}
	return 0
}

func (m *GetJournalStateResponseProto) GetHttpPort() uint32 {
	if m != nil && m.HttpPort != nil {
		return *m.HttpPort
	}
	return 0
}

func (m *GetJournalStateResponseProto) GetFromURL() string {
	if m != nil && m.FromURL != nil {
		return *m.FromURL
	}
	return ""
}

// *
// format()
type FormatRequestProto struct {
	Jid              *JournalIdProto                 `protobuf:"bytes,1,req,name=jid" json:"jid,omitempty"`
	NsInfo           *hadoop_hdfs.NamespaceInfoProto `protobuf:"bytes,2,req,name=nsInfo" json:"nsInfo,omitempty"`
	XXX_unrecognized []byte                          `json:"-"`
}

func (m *FormatRequestProto) Reset()         { *m = FormatRequestProto{} }
func (m *FormatRequestProto) String() string { return proto.CompactTextString(m) }
func (*FormatRequestProto) ProtoMessage()    {}

func (m *FormatRequestProto) GetJid() *JournalIdProto {
	if m != nil {
		return m.Jid
	}
	return nil
}

func (m *FormatRequestProto) GetNsInfo() *hadoop_hdfs.NamespaceInfoProto {
	if m != nil {
		return m.NsInfo
	}
	return nil
}

type FormatResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *FormatResponseProto) Reset()         { *m = FormatResponseProto{} }
func (m *FormatResponseProto) String() string { return proto.CompactTextString(m) }
func (*FormatResponseProto) ProtoMessage()    {}

// *
// newEpoch()
type NewEpochRequestProto struct {
	Jid              *JournalIdProto                 `protobuf:"bytes,1,req,name=jid" json:"jid,omitempty"`
	NsInfo           *hadoop_hdfs.NamespaceInfoProto `protobuf:"bytes,2,req,name=nsInfo" json:"nsInfo,omitempty"`
	Epoch            *uint64                         `protobuf:"varint,3,req,name=epoch" json:"epoch,omitempty"`
	XXX_unrecognized []byte                          `json:"-"`
}

func (m *NewEpochRequestProto) Reset()         { *m = NewEpochRequestProto{} }
func (m *NewEpochRequestProto) String() string { return proto.CompactTextString(m) }
func (*NewEpochRequestProto) ProtoMessage()    {}

func (m *NewEpochRequestProto) GetJid() *JournalIdProto {
	if m != nil {
		return m.Jid
	}
	return nil
}

func (m *NewEpochRequestProto) GetNsInfo() *hadoop_hdfs.NamespaceInfoProto {
	if m != nil {
		return m.NsInfo
	}
	return nil
}

func (m *NewEpochRequestProto) GetEpoch() uint64 {
	if m != nil && m.Epoch != nil {
		return *m.Epoch
	}
	return 0
}

type NewEpochResponseProto struct {
	LastSegmentTxId  *uint64 `protobuf:"varint,1,opt,name=lastSegmentTxId" json:"lastSegmentTxId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NewEpochResponseProto) Reset()         { *m = NewEpochResponseProto{} }
func (m *NewEpochResponseProto) String() string { return proto.CompactTextString(m) }
func (*NewEpochResponseProto) ProtoMessage()    {}

func (m *NewEpochResponseProto) GetLastSegmentTxId() uint64 {
	if m != nil && m.LastSegmentTxId != nil {
		return *m.LastSegmentTxId
	}
	return 0
}

// *
// getEditLogManifest()
type GetEditLogManifestRequestProto struct {
	Jid       *JournalIdProto `protobuf:"bytes,1,req,name=jid" json:"jid,omitempty"`
	SinceTxId *uint64         `protobuf:"varint,2,req,name=sinceTxId" json:"sinceTxId,omitempty"`
	// Whether or not the client will be reading from the returned streams.
	// optional bool forReading = 3 [default = true]; <obsolete, do not reuse>
	InProgressOk     *bool  `protobuf:"varint,4,opt,name=inProgressOk,def=0" json:"inProgressOk,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetEditLogManifestRequestProto) Reset()         { *m = GetEditLogManifestRequestProto{} }
func (m *GetEditLogManifestRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetEditLogManifestRequestProto) ProtoMessage()    {}

const Default_GetEditLogManifestRequestProto_InProgressOk bool = false

func (m *GetEditLogManifestRequestProto) GetJid() *JournalIdProto {
	if m != nil {
		return m.Jid
	}
	return nil
}

func (m *GetEditLogManifestRequestProto) GetSinceTxId() uint64 {
	if m != nil && m.SinceTxId != nil {
		return *m.SinceTxId
	}
	return 0
}

func (m *GetEditLogManifestRequestProto) GetInProgressOk() bool {
	if m != nil && m.InProgressOk != nil {
		return *m.InProgressOk
	}
	return Default_GetEditLogManifestRequestProto_InProgressOk
}

type GetEditLogManifestResponseProto struct {
	Manifest *hadoop_hdfs.RemoteEditLogManifestProto `protobuf:"bytes,1,req,name=manifest" json:"manifest,omitempty"`
	// Deprecated by fromURL
	HttpPort         *uint32 `protobuf:"varint,2,req,name=httpPort" json:"httpPort,omitempty"`
	FromURL          *string `protobuf:"bytes,3,opt,name=fromURL" json:"fromURL,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetEditLogManifestResponseProto) Reset()         { *m = GetEditLogManifestResponseProto{} }
func (m *GetEditLogManifestResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetEditLogManifestResponseProto) ProtoMessage()    {}

func (m *GetEditLogManifestResponseProto) GetManifest() *hadoop_hdfs.RemoteEditLogManifestProto {
	if m != nil {
		return m.Manifest
	}
	return nil
}

func (m *GetEditLogManifestResponseProto) GetHttpPort() uint32 {
	if m != nil && m.HttpPort != nil {
		return *m.HttpPort
	}
	return 0
}

func (m *GetEditLogManifestResponseProto) GetFromURL() string {
	if m != nil && m.FromURL != nil {
		return *m.FromURL
	}
	return ""
}

// *
// prepareRecovery()
type PrepareRecoveryRequestProto struct {
	ReqInfo          *RequestInfoProto `protobuf:"bytes,1,req,name=reqInfo" json:"reqInfo,omitempty"`
	SegmentTxId      *uint64           `protobuf:"varint,2,req,name=segmentTxId" json:"segmentTxId,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *PrepareRecoveryRequestProto) Reset()         { *m = PrepareRecoveryRequestProto{} }
func (m *PrepareRecoveryRequestProto) String() string { return proto.CompactTextString(m) }
func (*PrepareRecoveryRequestProto) ProtoMessage()    {}

func (m *PrepareRecoveryRequestProto) GetReqInfo() *RequestInfoProto {
	if m != nil {
		return m.ReqInfo
	}
	return nil
}

func (m *PrepareRecoveryRequestProto) GetSegmentTxId() uint64 {
	if m != nil && m.SegmentTxId != nil {
		return *m.SegmentTxId
	}
	return 0
}

type PrepareRecoveryResponseProto struct {
	SegmentState    *SegmentStateProto `protobuf:"bytes,1,opt,name=segmentState" json:"segmentState,omitempty"`
	AcceptedInEpoch *uint64            `protobuf:"varint,2,opt,name=acceptedInEpoch" json:"acceptedInEpoch,omitempty"`
	LastWriterEpoch *uint64            `protobuf:"varint,3,req,name=lastWriterEpoch" json:"lastWriterEpoch,omitempty"`
	// The highest committed txid that this logger has ever seen.
	// This may be higher than the data it actually has, in the case
	// that it was lagging before the old writer crashed.
	LastCommittedTxId *uint64 `protobuf:"varint,4,opt,name=lastCommittedTxId" json:"lastCommittedTxId,omitempty"`
	XXX_unrecognized  []byte  `json:"-"`
}

func (m *PrepareRecoveryResponseProto) Reset()         { *m = PrepareRecoveryResponseProto{} }
func (m *PrepareRecoveryResponseProto) String() string { return proto.CompactTextString(m) }
func (*PrepareRecoveryResponseProto) ProtoMessage()    {}

func (m *PrepareRecoveryResponseProto) GetSegmentState() *SegmentStateProto {
	if m != nil {
		return m.SegmentState
	}
	return nil
}

func (m *PrepareRecoveryResponseProto) GetAcceptedInEpoch() uint64 {
	if m != nil && m.AcceptedInEpoch != nil {
		return *m.AcceptedInEpoch
	}
	return 0
}

func (m *PrepareRecoveryResponseProto) GetLastWriterEpoch() uint64 {
	if m != nil && m.LastWriterEpoch != nil {
		return *m.LastWriterEpoch
	}
	return 0
}

func (m *PrepareRecoveryResponseProto) GetLastCommittedTxId() uint64 {
	if m != nil && m.LastCommittedTxId != nil {
		return *m.LastCommittedTxId
	}
	return 0
}

// *
// acceptRecovery()
type AcceptRecoveryRequestProto struct {
	ReqInfo *RequestInfoProto `protobuf:"bytes,1,req,name=reqInfo" json:"reqInfo,omitempty"`
	// * Details on the segment to recover
	StateToAccept *SegmentStateProto `protobuf:"bytes,2,req,name=stateToAccept" json:"stateToAccept,omitempty"`
	// * The URL from which the log may be copied
	FromURL          *string `protobuf:"bytes,3,req,name=fromURL" json:"fromURL,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AcceptRecoveryRequestProto) Reset()         { *m = AcceptRecoveryRequestProto{} }
func (m *AcceptRecoveryRequestProto) String() string { return proto.CompactTextString(m) }
func (*AcceptRecoveryRequestProto) ProtoMessage()    {}

func (m *AcceptRecoveryRequestProto) GetReqInfo() *RequestInfoProto {
	if m != nil {
		return m.ReqInfo
	}
	return nil
}

func (m *AcceptRecoveryRequestProto) GetStateToAccept() *SegmentStateProto {
	if m != nil {
		return m.StateToAccept
	}
	return nil
}

func (m *AcceptRecoveryRequestProto) GetFromURL() string {
	if m != nil && m.FromURL != nil {
		return *m.FromURL
	}
	return ""
}

type AcceptRecoveryResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *AcceptRecoveryResponseProto) Reset()         { *m = AcceptRecoveryResponseProto{} }
func (m *AcceptRecoveryResponseProto) String() string { return proto.CompactTextString(m) }
func (*AcceptRecoveryResponseProto) ProtoMessage()    {}

func init() {
}
