// Code generated by protoc-gen-go.
// source: InterDatanodeProtocol.proto
// DO NOT EDIT!

package hadoop_hdfs

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

// *
// Block with location information and new generation stamp
// to be used for recovery.
type InitReplicaRecoveryRequestProto struct {
	Block            *RecoveringBlockProto `protobuf:"bytes,1,req,name=block" json:"block,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *InitReplicaRecoveryRequestProto) Reset()         { *m = InitReplicaRecoveryRequestProto{} }
func (m *InitReplicaRecoveryRequestProto) String() string { return proto.CompactTextString(m) }
func (*InitReplicaRecoveryRequestProto) ProtoMessage()    {}

func (m *InitReplicaRecoveryRequestProto) GetBlock() *RecoveringBlockProto {
	if m != nil {
		return m.Block
	}
	return nil
}

// *
// Repica recovery information
type InitReplicaRecoveryResponseProto struct {
	ReplicaFound *bool `protobuf:"varint,1,req,name=replicaFound" json:"replicaFound,omitempty"`
	// The following entries are not set if there was no replica found.
	State            *ReplicaStateProto `protobuf:"varint,2,opt,name=state,enum=hadoop.hdfs.ReplicaStateProto" json:"state,omitempty"`
	Block            *BlockProto        `protobuf:"bytes,3,opt,name=block" json:"block,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *InitReplicaRecoveryResponseProto) Reset()         { *m = InitReplicaRecoveryResponseProto{} }
func (m *InitReplicaRecoveryResponseProto) String() string { return proto.CompactTextString(m) }
func (*InitReplicaRecoveryResponseProto) ProtoMessage()    {}

func (m *InitReplicaRecoveryResponseProto) GetReplicaFound() bool {
	if m != nil && m.ReplicaFound != nil {
		return *m.ReplicaFound
	}
	return false
}

func (m *InitReplicaRecoveryResponseProto) GetState() ReplicaStateProto {
	if m != nil && m.State != nil {
		return *m.State
	}
	return ReplicaStateProto_FINALIZED
}

func (m *InitReplicaRecoveryResponseProto) GetBlock() *BlockProto {
	if m != nil {
		return m.Block
	}
	return nil
}

// *
// Update replica with new generation stamp and length
type UpdateReplicaUnderRecoveryRequestProto struct {
	Block            *ExtendedBlockProto `protobuf:"bytes,1,req,name=block" json:"block,omitempty"`
	RecoveryId       *uint64             `protobuf:"varint,2,req,name=recoveryId" json:"recoveryId,omitempty"`
	NewLength        *uint64             `protobuf:"varint,3,req,name=newLength" json:"newLength,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *UpdateReplicaUnderRecoveryRequestProto) Reset() {
	*m = UpdateReplicaUnderRecoveryRequestProto{}
}
func (m *UpdateReplicaUnderRecoveryRequestProto) String() string { return proto.CompactTextString(m) }
func (*UpdateReplicaUnderRecoveryRequestProto) ProtoMessage()    {}

func (m *UpdateReplicaUnderRecoveryRequestProto) GetBlock() *ExtendedBlockProto {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *UpdateReplicaUnderRecoveryRequestProto) GetRecoveryId() uint64 {
	if m != nil && m.RecoveryId != nil {
		return *m.RecoveryId
	}
	return 0
}

func (m *UpdateReplicaUnderRecoveryRequestProto) GetNewLength() uint64 {
	if m != nil && m.NewLength != nil {
		return *m.NewLength
	}
	return 0
}

// *
// Response returns updated block information
type UpdateReplicaUnderRecoveryResponseProto struct {
	StorageUuid      *string `protobuf:"bytes,1,opt,name=storageUuid" json:"storageUuid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UpdateReplicaUnderRecoveryResponseProto) Reset() {
	*m = UpdateReplicaUnderRecoveryResponseProto{}
}
func (m *UpdateReplicaUnderRecoveryResponseProto) String() string { return proto.CompactTextString(m) }
func (*UpdateReplicaUnderRecoveryResponseProto) ProtoMessage()    {}

func (m *UpdateReplicaUnderRecoveryResponseProto) GetStorageUuid() string {
	if m != nil && m.StorageUuid != nil {
		return *m.StorageUuid
	}
	return ""
}

func init() {
}
