// Code generated by protoc-gen-go.
// source: NamenodeProtocol.proto
// DO NOT EDIT!

/*
Package hadoop_hdfs_namenode is a generated protocol buffer package.

It is generated from these files:
	NamenodeProtocol.proto

It has these top-level messages:
	GetBlocksRequestProto
	GetBlocksResponseProto
	GetBlockKeysRequestProto
	GetBlockKeysResponseProto
	GetTransactionIdRequestProto
	GetTransactionIdResponseProto
	RollEditLogRequestProto
	RollEditLogResponseProto
	GetMostRecentCheckpointTxIdRequestProto
	GetMostRecentCheckpointTxIdResponseProto
	ErrorReportRequestProto
	ErrorReportResponseProto
	RegisterRequestProto
	RegisterResponseProto
	StartCheckpointRequestProto
	StartCheckpointResponseProto
	EndCheckpointRequestProto
	EndCheckpointResponseProto
	GetEditLogManifestRequestProto
	GetEditLogManifestResponseProto
*/
package hadoop_hdfs_namenode

import proto "code.google.com/p/goprotobuf/proto"
import math "math"
import hadoop_hdfs "github.com/hortonworks/gohadoop/hdfs"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

// *
// Get list of blocks for a given datanode with the total length
// of adding up to given size
// datanode - Datanode ID to get list of block from
// size - size to which the block lengths must add up to
type GetBlocksRequestProto struct {
	Datanode         *hadoop_hdfs.DatanodeIDProto `protobuf:"bytes,1,req,name=datanode" json:"datanode,omitempty"`
	Size             *uint64                      `protobuf:"varint,2,req,name=size" json:"size,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *GetBlocksRequestProto) Reset()         { *m = GetBlocksRequestProto{} }
func (m *GetBlocksRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetBlocksRequestProto) ProtoMessage()    {}

func (m *GetBlocksRequestProto) GetDatanode() *hadoop_hdfs.DatanodeIDProto {
	if m != nil {
		return m.Datanode
	}
	return nil
}

func (m *GetBlocksRequestProto) GetSize() uint64 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

// *
// blocks - List of returned blocks
type GetBlocksResponseProto struct {
	Blocks           *hadoop_hdfs.BlocksWithLocationsProto `protobuf:"bytes,1,req,name=blocks" json:"blocks,omitempty"`
	XXX_unrecognized []byte                                `json:"-"`
}

func (m *GetBlocksResponseProto) Reset()         { *m = GetBlocksResponseProto{} }
func (m *GetBlocksResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetBlocksResponseProto) ProtoMessage()    {}

func (m *GetBlocksResponseProto) GetBlocks() *hadoop_hdfs.BlocksWithLocationsProto {
	if m != nil {
		return m.Blocks
	}
	return nil
}

// *
// void request
type GetBlockKeysRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetBlockKeysRequestProto) Reset()         { *m = GetBlockKeysRequestProto{} }
func (m *GetBlockKeysRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetBlockKeysRequestProto) ProtoMessage()    {}

// *
// keys - Information about block keys at the active namenode
type GetBlockKeysResponseProto struct {
	Keys             *hadoop_hdfs.ExportedBlockKeysProto `protobuf:"bytes,1,opt,name=keys" json:"keys,omitempty"`
	XXX_unrecognized []byte                              `json:"-"`
}

func (m *GetBlockKeysResponseProto) Reset()         { *m = GetBlockKeysResponseProto{} }
func (m *GetBlockKeysResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetBlockKeysResponseProto) ProtoMessage()    {}

func (m *GetBlockKeysResponseProto) GetKeys() *hadoop_hdfs.ExportedBlockKeysProto {
	if m != nil {
		return m.Keys
	}
	return nil
}

// *
// void request
type GetTransactionIdRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetTransactionIdRequestProto) Reset()         { *m = GetTransactionIdRequestProto{} }
func (m *GetTransactionIdRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetTransactionIdRequestProto) ProtoMessage()    {}

// *
// txId - Transaction ID of the most recently persisted edit log record
type GetTransactionIdResponseProto struct {
	TxId             *uint64 `protobuf:"varint,1,req,name=txId" json:"txId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetTransactionIdResponseProto) Reset()         { *m = GetTransactionIdResponseProto{} }
func (m *GetTransactionIdResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetTransactionIdResponseProto) ProtoMessage()    {}

func (m *GetTransactionIdResponseProto) GetTxId() uint64 {
	if m != nil && m.TxId != nil {
		return *m.TxId
	}
	return 0
}

// *
// void request
type RollEditLogRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RollEditLogRequestProto) Reset()         { *m = RollEditLogRequestProto{} }
func (m *RollEditLogRequestProto) String() string { return proto.CompactTextString(m) }
func (*RollEditLogRequestProto) ProtoMessage()    {}

// *
// signature - A unique token to identify checkpoint transaction
type RollEditLogResponseProto struct {
	Signature        *hadoop_hdfs.CheckpointSignatureProto `protobuf:"bytes,1,req,name=signature" json:"signature,omitempty"`
	XXX_unrecognized []byte                                `json:"-"`
}

func (m *RollEditLogResponseProto) Reset()         { *m = RollEditLogResponseProto{} }
func (m *RollEditLogResponseProto) String() string { return proto.CompactTextString(m) }
func (*RollEditLogResponseProto) ProtoMessage()    {}

func (m *RollEditLogResponseProto) GetSignature() *hadoop_hdfs.CheckpointSignatureProto {
	if m != nil {
		return m.Signature
	}
	return nil
}

// *
// void request
type GetMostRecentCheckpointTxIdRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetMostRecentCheckpointTxIdRequestProto) Reset() {
	*m = GetMostRecentCheckpointTxIdRequestProto{}
}
func (m *GetMostRecentCheckpointTxIdRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetMostRecentCheckpointTxIdRequestProto) ProtoMessage()    {}

type GetMostRecentCheckpointTxIdResponseProto struct {
	TxId             *uint64 `protobuf:"varint,1,req,name=txId" json:"txId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetMostRecentCheckpointTxIdResponseProto) Reset() {
	*m = GetMostRecentCheckpointTxIdResponseProto{}
}
func (m *GetMostRecentCheckpointTxIdResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetMostRecentCheckpointTxIdResponseProto) ProtoMessage()    {}

func (m *GetMostRecentCheckpointTxIdResponseProto) GetTxId() uint64 {
	if m != nil && m.TxId != nil {
		return *m.TxId
	}
	return 0
}

// *
// registration - Namenode reporting the error
// errorCode - error code indicating the error
// msg - Free text description of the error
type ErrorReportRequestProto struct {
	Registration     *hadoop_hdfs.NamenodeRegistrationProto `protobuf:"bytes,1,req,name=registration" json:"registration,omitempty"`
	ErrorCode        *uint32                                `protobuf:"varint,2,req,name=errorCode" json:"errorCode,omitempty"`
	Msg              *string                                `protobuf:"bytes,3,req,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte                                 `json:"-"`
}

func (m *ErrorReportRequestProto) Reset()         { *m = ErrorReportRequestProto{} }
func (m *ErrorReportRequestProto) String() string { return proto.CompactTextString(m) }
func (*ErrorReportRequestProto) ProtoMessage()    {}

func (m *ErrorReportRequestProto) GetRegistration() *hadoop_hdfs.NamenodeRegistrationProto {
	if m != nil {
		return m.Registration
	}
	return nil
}

func (m *ErrorReportRequestProto) GetErrorCode() uint32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

func (m *ErrorReportRequestProto) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

// *
// void response
type ErrorReportResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ErrorReportResponseProto) Reset()         { *m = ErrorReportResponseProto{} }
func (m *ErrorReportResponseProto) String() string { return proto.CompactTextString(m) }
func (*ErrorReportResponseProto) ProtoMessage()    {}

// *
// registration - Information of the namenode registering with primary namenode
type RegisterRequestProto struct {
	Registration     *hadoop_hdfs.NamenodeRegistrationProto `protobuf:"bytes,1,req,name=registration" json:"registration,omitempty"`
	XXX_unrecognized []byte                                 `json:"-"`
}

func (m *RegisterRequestProto) Reset()         { *m = RegisterRequestProto{} }
func (m *RegisterRequestProto) String() string { return proto.CompactTextString(m) }
func (*RegisterRequestProto) ProtoMessage()    {}

func (m *RegisterRequestProto) GetRegistration() *hadoop_hdfs.NamenodeRegistrationProto {
	if m != nil {
		return m.Registration
	}
	return nil
}

// *
// registration - Updated registration information of the newly registered
//                datanode.
type RegisterResponseProto struct {
	Registration     *hadoop_hdfs.NamenodeRegistrationProto `protobuf:"bytes,1,req,name=registration" json:"registration,omitempty"`
	XXX_unrecognized []byte                                 `json:"-"`
}

func (m *RegisterResponseProto) Reset()         { *m = RegisterResponseProto{} }
func (m *RegisterResponseProto) String() string { return proto.CompactTextString(m) }
func (*RegisterResponseProto) ProtoMessage()    {}

func (m *RegisterResponseProto) GetRegistration() *hadoop_hdfs.NamenodeRegistrationProto {
	if m != nil {
		return m.Registration
	}
	return nil
}

// *
// Start checkpoint request
// registration - Namenode that is starting the checkpoint
type StartCheckpointRequestProto struct {
	Registration     *hadoop_hdfs.NamenodeRegistrationProto `protobuf:"bytes,1,req,name=registration" json:"registration,omitempty"`
	XXX_unrecognized []byte                                 `json:"-"`
}

func (m *StartCheckpointRequestProto) Reset()         { *m = StartCheckpointRequestProto{} }
func (m *StartCheckpointRequestProto) String() string { return proto.CompactTextString(m) }
func (*StartCheckpointRequestProto) ProtoMessage()    {}

func (m *StartCheckpointRequestProto) GetRegistration() *hadoop_hdfs.NamenodeRegistrationProto {
	if m != nil {
		return m.Registration
	}
	return nil
}

// *
// command - Command returned by the active namenode to be
//           be handled by the caller.
type StartCheckpointResponseProto struct {
	Command          *hadoop_hdfs.NamenodeCommandProto `protobuf:"bytes,1,req,name=command" json:"command,omitempty"`
	XXX_unrecognized []byte                            `json:"-"`
}

func (m *StartCheckpointResponseProto) Reset()         { *m = StartCheckpointResponseProto{} }
func (m *StartCheckpointResponseProto) String() string { return proto.CompactTextString(m) }
func (*StartCheckpointResponseProto) ProtoMessage()    {}

func (m *StartCheckpointResponseProto) GetCommand() *hadoop_hdfs.NamenodeCommandProto {
	if m != nil {
		return m.Command
	}
	return nil
}

// *
// End or finalize the previously started checkpoint
// registration - Namenode that is ending the checkpoint
// signature - unique token to identify checkpoint transaction,
//             that was received when checkpoint was started.
type EndCheckpointRequestProto struct {
	Registration     *hadoop_hdfs.NamenodeRegistrationProto `protobuf:"bytes,1,req,name=registration" json:"registration,omitempty"`
	Signature        *hadoop_hdfs.CheckpointSignatureProto  `protobuf:"bytes,2,req,name=signature" json:"signature,omitempty"`
	XXX_unrecognized []byte                                 `json:"-"`
}

func (m *EndCheckpointRequestProto) Reset()         { *m = EndCheckpointRequestProto{} }
func (m *EndCheckpointRequestProto) String() string { return proto.CompactTextString(m) }
func (*EndCheckpointRequestProto) ProtoMessage()    {}

func (m *EndCheckpointRequestProto) GetRegistration() *hadoop_hdfs.NamenodeRegistrationProto {
	if m != nil {
		return m.Registration
	}
	return nil
}

func (m *EndCheckpointRequestProto) GetSignature() *hadoop_hdfs.CheckpointSignatureProto {
	if m != nil {
		return m.Signature
	}
	return nil
}

// *
// void response
type EndCheckpointResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *EndCheckpointResponseProto) Reset()         { *m = EndCheckpointResponseProto{} }
func (m *EndCheckpointResponseProto) String() string { return proto.CompactTextString(m) }
func (*EndCheckpointResponseProto) ProtoMessage()    {}

// *
// sinceTxId - return the editlog information for transactions >= sinceTxId
type GetEditLogManifestRequestProto struct {
	SinceTxId        *uint64 `protobuf:"varint,1,req,name=sinceTxId" json:"sinceTxId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetEditLogManifestRequestProto) Reset()         { *m = GetEditLogManifestRequestProto{} }
func (m *GetEditLogManifestRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetEditLogManifestRequestProto) ProtoMessage()    {}

func (m *GetEditLogManifestRequestProto) GetSinceTxId() uint64 {
	if m != nil && m.SinceTxId != nil {
		return *m.SinceTxId
	}
	return 0
}

// *
// manifest - Enumeration of editlogs from namenode for
//            logs >= sinceTxId in the request
type GetEditLogManifestResponseProto struct {
	Manifest         *hadoop_hdfs.RemoteEditLogManifestProto `protobuf:"bytes,1,req,name=manifest" json:"manifest,omitempty"`
	XXX_unrecognized []byte                                  `json:"-"`
}

func (m *GetEditLogManifestResponseProto) Reset()         { *m = GetEditLogManifestResponseProto{} }
func (m *GetEditLogManifestResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetEditLogManifestResponseProto) ProtoMessage()    {}

func (m *GetEditLogManifestResponseProto) GetManifest() *hadoop_hdfs.RemoteEditLogManifestProto {
	if m != nil {
		return m.Manifest
	}
	return nil
}

func init() {
}
